# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bookland}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hakan Ensari", "Piotr Laszewski"]
  s.date = %q{2010-09-09}
  s.description = %q{A simple ISBN class in Ruby}
  s.email = %q{code@papercavalier.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     ".rspec",
     ".rvmrc",
     "Gemfile",
     "Gemfile.lock",
     "History.md",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bookland.gemspec",
     "lib/bookland.rb",
     "spec/bookland_spec.rb",
     "spec/fixtures/isbn",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/papercavalier/bookland}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple ISBN class in Ruby}
  s.test_files = [
    "spec/bookland_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

